apiVersion: v1
kind: Service
metadata:
  name: jfrog-cloud-svc
  labels:
    app: jfrog-cloud-svc
spec:
  type: NodePort
  selector:
    app: jfrog-cloud-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 8081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jfrog-cloud-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jfrog-cloud-app
    spec:
      containers:
        - name: jfrog-cloud-app
          image: jfrog-cloud-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080